name: Minecraft Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/0xkowalskidev/minecraft-server:latest

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/0xkowalskidev/minecraft-server:latest

